name: Lint-CSS (Stylelint)

on:
  pull_request:

jobs:
  stylelint:
    name: Run stylelint scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: stylelint
        uses: actions-hub/stylelint@master
        env:
            CONFIG_PATH: ./
